import json
import zlib
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from glob import glob
from pathlib import Path

import networkx as nx

from stepzero.algorithms.topological_sort import topological_sort
from stepzero.graph_queries import concept_depths
from stepzero.profile_validation import ProfileValidationError, validate_profile
from stepzero.student import ConceptProgress, LearningEvent, LearningEventType, MasteryStatus, Student

PROFILES_DIR = Path(__file__).resolve().parent.parent / "data" / "students"

PROFILE_GENERATOR_VERSION = "1.0"

# Fixed anchor date so regenerating a profile always produces identical timestamps.
PROFILE_EPOCH = datetime(2025, 1, 6, 9, 0, 0)

# Crammed concepts land in a narrow band, a shallow pass rather than a failure.
CRAMMED_MASTERY_FLOOR = 0.52
CRAMMED_MASTERY_CEILING = 0.62

DISCLAIMER = (
    "Synthetic research persona generated by stepzero.student_profiles. This is designed "
    "test material, not observed data, and it is not derived from or calibrated against any "
    "real student. It exists to give Project Step Zero v1.0 controlled, reproducible inputs "
    "for recommendation, simulation, and evaluation experiments, and is expected to be "
    "replaced or calibrated once primary research data is collected."
)


class ProfileError(Exception):
    pass


@dataclass(frozen=True)
class PersonaSpec:
    student_id: str
    name: str
    persona: str
    description: str
    design_notes: tuple[str, ...]

    # Coverage, which concepts this learner has ever opened
    subject_reach: dict[str, int]
    subject_coverage: dict[str, float]
    required: tuple[str, ...] = ()

    # Mastery model, applied to every touched concept
    base_mastery: float = 0.7
    depth_decay: float = 0.04
    category_modifiers: dict[str, float] = field(default_factory=dict)
    jitter: float = 0.10
    mastery_threshold: float = 0.75

    # Effort model
    attempts_base: float = 1.5
    attempts_per_missing_mastery: float = 3.0
    hours_multiplier: float = 1.0

    # Self assessment bias, positive means the learner overrates themselves
    confidence_bias: float = 0.0

    # Deliberate, documented departures from the smooth model
    gaps: dict[str, float] = field(default_factory=dict)
    bright_spots: dict[str, float] = field(default_factory=dict)
    forgotten: tuple[str, ...] = ()
    crammed: tuple[str, ...] = ()

    # Study calendar, in weeks relative to PROFILE_EPOCH
    study_start_week: int = 0
    study_weeks: int = 20


def _stable_unit(*parts: str) -> float:
    # Deterministic value in [0, 1), stable across runs, processes, and platforms.
    key = "|".join(parts).encode("utf-8")
    return (zlib.crc32(key) % 100_000) / 100_000.0


def _clamp(value: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, value))


def _category_of(graph: nx.DiGraph, concept_id: str) -> str:
    return graph.nodes[concept_id].get("category", "uncategorized")


def _subject_of(concept_id: str) -> str:
    return concept_id.split(".", 1)[0]


def _forced_concepts(spec: PersonaSpec, graph: nx.DiGraph) -> set[str]:
    # Concepts the persona definition pins in place regardless of the coverage draw.
    forced = set(spec.crammed) | set(spec.bright_spots) | set(spec.gaps) | set(spec.forgotten)
    for concept_id in spec.required:
        if concept_id not in graph.nodes:
            raise ProfileError(
                f"Persona '{spec.student_id}' requires '{concept_id}', which is not in the graph."
            )
        forced.add(concept_id)
        forced |= nx.ancestors(graph, concept_id)
    return forced


def _select_touched(
    spec: PersonaSpec, graph: nx.DiGraph, depths: dict[str, int], order: list[str]
) -> list[str]:
    # Walking topological order keeps study sequence prerequisite-aware by construction.
    forced = _forced_concepts(spec, graph)
    touched: list[str] = []
    touched_set: set[str] = set()

    for concept_id in order:
        if concept_id in forced:
            touched.append(concept_id)
            touched_set.add(concept_id)
            continue

        subject = _subject_of(concept_id)
        reach = spec.subject_reach.get(subject)
        if reach is None or depths[concept_id] > reach:
            continue

        # A learner normally opens a concept only after opening its prerequisites.
        if not set(graph.predecessors(concept_id)).issubset(touched_set):
            continue

        # The coverage draw only bites near the persona's reach, never at foundations.
        coverage = spec.subject_coverage.get(subject, 1.0)
        depth_fraction = depths[concept_id] / max(1, reach)
        effective_coverage = coverage + (1 - coverage) * (1 - depth_fraction)

        if _stable_unit(spec.student_id, concept_id, "coverage") < effective_coverage:
            touched.append(concept_id)
            touched_set.add(concept_id)

    return touched


def _target_mastery(
    spec: PersonaSpec, graph: nx.DiGraph, concept_id: str, depths: dict[str, int]
) -> float:
    if concept_id in spec.gaps:
        return _clamp(spec.gaps[concept_id])
    if concept_id in spec.bright_spots:
        return _clamp(spec.bright_spots[concept_id])

    value = spec.base_mastery
    value -= spec.depth_decay * depths[concept_id]
    value += spec.category_modifiers.get(_category_of(graph, concept_id), 0.0)
    value += (_stable_unit(spec.student_id, concept_id, "mastery") - 0.5) * spec.jitter

    # Knowledge that was mastered long ago and never revisited has decayed.
    if concept_id in spec.forgotten:
        value *= 0.5
    # Crammed material was drilled to a shallow pass, neither solid nor failed.
    if concept_id in spec.crammed:
        value = _clamp(value, CRAMMED_MASTERY_FLOOR, CRAMMED_MASTERY_CEILING)

    return _clamp(value)


def _attempt_count(spec: PersonaSpec, concept_id: str, mastery: float) -> int:
    missing = 1.0 - mastery
    raw = spec.attempts_base + spec.attempts_per_missing_mastery * missing
    raw += (_stable_unit(spec.student_id, concept_id, "attempts") - 0.5) * 1.2
    return max(1, round(raw))


def _attempt_scores(spec: PersonaSpec, concept_id: str, mastery: float, attempts: int) -> list[float]:
    # Earlier attempts sit below the final level so each concept shows a learning curve.
    scores = []
    for i in range(attempts):
        ramp = 0.22 * (attempts - 1 - i) / (attempts - 1) if attempts > 1 else 0.0
        noise = (_stable_unit(spec.student_id, concept_id, f"attempt{i}") - 0.5) * 0.08
        scores.append(round(_clamp(mastery - ramp + noise), 3))
    return scores


def _build_metadata(spec: PersonaSpec) -> dict:
    return {
        "synthetic": True,
        "persona": spec.persona,
        "description": spec.description,
        "disclaimer": DISCLAIMER,
        "generator_version": PROFILE_GENERATOR_VERSION,
        "design_notes": list(spec.design_notes),
    }


def build_profile(spec: PersonaSpec, graph: nx.DiGraph) -> Student:
    # Records are built directly because start_concept and record_attempt stamp datetime.now().
    depths = concept_depths(graph)
    if depths is None:
        raise ProfileError("Cannot build profiles against a graph that contains a cycle.")

    order = topological_sort(graph).order
    touched = _select_touched(spec, graph, depths, order)

    created_at = PROFILE_EPOCH + timedelta(days=spec.study_start_week * 7 - 3)
    student = Student(
        student_id=spec.student_id,
        name=spec.name,
        created_at=created_at,
        metadata=_build_metadata(spec),
    )

    span_days = spec.study_weeks * 7
    start_day = spec.study_start_week * 7

    for index, concept_id in enumerate(touched):
        mastery = round(_target_mastery(spec, graph, concept_id, depths), 4)
        attempts = _attempt_count(spec, concept_id, mastery)
        is_mastered = (
            mastery >= spec.mastery_threshold
            or concept_id in spec.forgotten
            or concept_id in spec.crammed
        )

        estimated_hours = graph.nodes[concept_id].get("estimated_study_hours", 3.0)
        effort_spread = 0.85 + 0.3 * _stable_unit(spec.student_id, concept_id, "hours")
        hours = estimated_hours * spec.hours_multiplier * (1 + 0.35 * (attempts - 1)) * effort_spread

        confidence = _clamp(
            mastery
            + spec.confidence_bias
            + (_stable_unit(spec.student_id, concept_id, "confidence") - 0.5) * 0.08
        )

        position = index / (len(touched) - 1) if len(touched) > 1 else 0.0
        day_offset = start_day + position * span_days
        hour_offset = int(_stable_unit(spec.student_id, concept_id, "hour") * 10)
        first_studied = PROFILE_EPOCH + timedelta(days=round(day_offset), hours=hour_offset)

        review_gap = attempts * 3 + int(_stable_unit(spec.student_id, concept_id, "gap") * 5)
        last_reviewed = first_studied + timedelta(days=review_gap)

        student.progress[concept_id] = ConceptProgress(
            concept_id=concept_id,
            status=MasteryStatus.MASTERED if is_mastered else MasteryStatus.IN_PROGRESS,
            mastery_score=mastery,
            attempts=attempts,
            time_spent_hours=round(hours, 2),
            self_rated_confidence=round(confidence, 2),
            first_studied_at=first_studied,
            last_reviewed_at=last_reviewed,
            completed_at=last_reviewed if is_mastered else None,
        )

        student.history.append(
            LearningEvent(
                concept_id=concept_id,
                event_type=LearningEventType.STARTED,
                timestamp=first_studied,
                details={},
            )
        )

        scores = _attempt_scores(spec, concept_id, mastery, attempts)
        for i, score in enumerate(scores):
            fraction = (i + 1) / attempts
            student.history.append(
                LearningEvent(
                    concept_id=concept_id,
                    event_type=LearningEventType.ATTEMPTED,
                    timestamp=first_studied + (last_reviewed - first_studied) * fraction,
                    details={
                        "score": score,
                        "time_spent_hours": round(hours / attempts, 2),
                        "self_rated_confidence": round(confidence, 2),
                    },
                )
            )

        if is_mastered:
            student.history.append(
                LearningEvent(
                    concept_id=concept_id,
                    event_type=LearningEventType.MASTERED,
                    timestamp=last_reviewed,
                    details={"mastery_score": mastery},
                )
            )

    student.history.sort(key=lambda e: e.timestamp)
    return student


# Persona definitions

BEGINNER = PersonaSpec(
    student_id="beginner_student",
    name="Beginner Student",
    persona="beginner",
    description=(
        "Early-stage learner working through foundational mathematics with a first look at "
        "biology and programming. Most concepts are still in progress rather than mastered."
    ),
    design_notes=(
        "Reach is capped at shallow prerequisite depths, so nearly everything studied is foundational.",
        "Arithmetic is the clear strength, geometry is the clear weakness.",
        "variables_and_types is a deliberate bright spot from self-taught hobby programming.",
        "euclidean_basics is a deliberate gap, studied but never solidified.",
    ),
    subject_reach={"mathematics": 3, "biology": 2, "computer_science": 2},
    subject_coverage={"mathematics": 0.90, "biology": 1.0, "computer_science": 0.70},
    base_mastery=0.68,
    depth_decay=0.050,
    category_modifiers={
        "arithmetic": 0.20,
        "algebra": 0.05,
        "geometry": -0.12,
        "statistics": -0.08,
        "cellular": 0.08,
        "foundations": 0.05,
    },
    jitter=0.10,
    mastery_threshold=0.70,
    attempts_base=1.6,
    attempts_per_missing_mastery=3.2,
    hours_multiplier=1.15,
    confidence_bias=-0.05,
    gaps={"mathematics.geometry.euclidean_basics": 0.38},
    bright_spots={"computer_science.programming.variables_and_types": 0.84},
    study_start_week=0,
    study_weeks=10,
)

INTERMEDIATE = PersonaSpec(
    student_id="intermediate_student",
    name="Intermediate Student",
    persona="intermediate",
    description=(
        "Mid-curriculum learner with solid algebra and precalculus, a weak statistics track, "
        "and a growing programming practice. Carries one decayed foundation from a year ago."
    ),
    design_notes=(
        "Algebra and programming are strengths, statistics and geometry are weaknesses.",
        "probability_basics is deliberately forgotten, mastered long ago and now decayed, "
        "which drags on every downstream concept that depends on it.",
        "combinatorics is a deliberate gap that blocks a statistics branch.",
        "recursion is a deliberate bright spot that outruns the surrounding programming work.",
    ),
    subject_reach={"mathematics": 5, "computer_science": 5, "biology": 4},
    subject_coverage={"mathematics": 0.92, "computer_science": 0.80, "biology": 0.60},
    base_mastery=0.74,
    depth_decay=0.035,
    category_modifiers={
        "arithmetic": 0.12,
        "algebra": 0.10,
        "precalculus": 0.06,
        "statistics": -0.18,
        "geometry": -0.10,
        "programming": 0.08,
        "data_structures": -0.05,
    },
    jitter=0.10,
    mastery_threshold=0.75,
    attempts_base=1.5,
    attempts_per_missing_mastery=3.0,
    hours_multiplier=1.0,
    confidence_bias=0.03,
    gaps={"mathematics.statistics.combinatorics": 0.41},
    bright_spots={"computer_science.programming.recursion": 0.88},
    forgotten=("mathematics.statistics.probability_basics",),
    study_start_week=0,
    study_weeks=30,
)

ADVANCED = PersonaSpec(
    student_id="advanced_student",
    name="Advanced Student",
    persona="advanced",
    description=(
        "Late-stage learner with deep mathematics and physics coverage, competent computer "
        "science, and only an introductory brush with chemistry. Learns quickly and reviews little."
    ),
    design_notes=(
        "Full mathematics coverage is what makes the deep physics track reachable at all.",
        "Chemistry reach is deliberately shallow so the profile is strong but not uniformly strong.",
        "probability_distributions is a deliberate gap from avoiding the statistics track.",
        "euclidean_basics is deliberately forgotten, an early topic never revisited in years.",
    ),
    subject_reach={"mathematics": 10, "physics": 11, "computer_science": 7, "chemistry": 2},
    subject_coverage={
        "mathematics": 1.0,
        "physics": 0.90,
        "computer_science": 0.75,
        "chemistry": 0.50,
    },
    base_mastery=0.92,
    depth_decay=0.015,
    category_modifiers={
        "calculus": 0.06,
        "linear_algebra": 0.05,
        "mechanics": 0.04,
        "modern_physics": -0.05,
        "statistics": -0.10,
        "atomic_structure": -0.12,
        "algorithms": 0.02,
    },
    jitter=0.08,
    mastery_threshold=0.78,
    attempts_base=1.1,
    attempts_per_missing_mastery=1.8,
    hours_multiplier=0.75,
    confidence_bias=0.04,
    gaps={"mathematics.statistics.probability_distributions": 0.55},
    bright_spots={"physics.modern_physics.special_relativity": 0.93},
    forgotten=("mathematics.geometry.euclidean_basics",),
    study_start_week=0,
    study_weeks=80,
)

STRUGGLING = PersonaSpec(
    student_id="struggling_student",
    name="Struggling Student",
    persona="struggling",
    description=(
        "High-effort learner who invests far more hours per concept than anyone else and still "
        "masters few of them. Quantitative work is hard, descriptive biology genuinely is not."
    ),
    design_notes=(
        "Biology categories carry large positive modifiers so the profile is not uniformly weak, "
        "which is the point, a struggling learner is not weak at everything.",
        "Attempt counts and hours per concept are the highest of any persona.",
        "Confidence is biased downward, this learner underrates real ability.",
        "chemical_bonding and dna_structure are pinned as required so the descriptive biology "
        "track this learner is actually good at cannot be lost to a coverage draw, and because "
        "that track depends on chemistry across subjects.",
        "redox is deliberately out of reach, so cellular_respiration stays blocked behind it.",
        "mendelian_genetics is a deliberate bright spot, linear_equations a deliberate gap.",
    ),
    subject_reach={"mathematics": 3, "biology": 5, "chemistry": 2},
    subject_coverage={"mathematics": 0.85, "biology": 0.92, "chemistry": 0.60},
    required=("chemistry.bonding.chemical_bonding", "biology.genetics.dna_structure"),
    base_mastery=0.58,
    depth_decay=0.045,
    category_modifiers={
        "arithmetic": 0.15,
        "algebra": -0.10,
        "geometry": -0.05,
        "statistics": -0.12,
        "cellular": 0.22,
        "genetics": 0.18,
        "physiology": 0.15,
        "atomic_structure": -0.10,
        "stoichiometry": -0.18,
    },
    jitter=0.12,
    mastery_threshold=0.68,
    attempts_base=2.8,
    attempts_per_missing_mastery=4.5,
    hours_multiplier=1.70,
    confidence_bias=-0.16,
    gaps={"mathematics.algebra.linear_equations": 0.33},
    bright_spots={"biology.genetics.mendelian_genetics": 0.86},
    study_start_week=0,
    study_weeks=40,
)

EXAM_FOCUSED = PersonaSpec(
    student_id="exam_focused_student",
    name="Exam Focused Student",
    persona="exam_focused",
    description=(
        "Broad, shallow, recent coverage driven by an exam syllabus rather than the prerequisite "
        "graph. Passes advanced topics without the foundations underneath them and overrates "
        "their own understanding."
    ),
    design_notes=(
        "The only persona that studies out of prerequisite order, which is the behaviour it "
        "exists to stress-test.",
        "chemical_equilibrium, ph_and_buffers, and integrals are crammed, mastered on paper "
        "while their prerequisites were never opened.",
        "Hours per concept are the lowest of any persona and the mastery bar is the lowest, "
        "so the learner moves on quickly.",
        "Confidence is biased upward, the mirror image of the struggling persona.",
        "limits is a deliberate gap, the module was passed without the idea ever landing.",
    ),
    subject_reach={"mathematics": 7, "chemistry": 4, "biology": 5, "physics": 2},
    subject_coverage={
        "mathematics": 0.75,
        "chemistry": 0.90,
        "biology": 0.80,
        "physics": 0.80,
    },
    base_mastery=0.66,
    depth_decay=0.030,
    category_modifiers={
        "acids_bases": 0.08,
        "organic": 0.06,
        "genetics": 0.05,
        "calculus": -0.12,
        "linear_algebra": -0.15,
        "electromagnetism": -0.05,
    },
    jitter=0.11,
    mastery_threshold=0.64,
    attempts_base=1.2,
    attempts_per_missing_mastery=2.0,
    hours_multiplier=0.55,
    confidence_bias=0.18,
    gaps={"mathematics.calculus.limits": 0.42},
    crammed=(
        "chemistry.equilibrium.chemical_equilibrium",
        "chemistry.acids_bases.ph_and_buffers",
        "mathematics.calculus.integrals",
    ),
    study_start_week=60,
    study_weeks=14,
)

PERSONAS: list[PersonaSpec] = [BEGINNER, INTERMEDIATE, ADVANCED, STRUGGLING, EXAM_FOCUSED]


# Generation and loading

def write_profile_files(
    graph: nx.DiGraph,
    output_dir: str | Path = PROFILES_DIR,
    specs: list[PersonaSpec] | None = None,
) -> list[Path]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for spec in specs if specs is not None else PERSONAS:
        student = build_profile(spec, graph)
        data = student.to_dict()

        # Generated files are validated before they are written, never after.
        validate_profile(data, graph=graph, raise_on_error=True)

        path = output_dir / f"{spec.student_id}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        written.append(path)
    return written


def load_profile(
    path: str | Path, graph: nx.DiGraph | None = None, validate: bool = True
) -> Student:
    path = Path(path)
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if validate:
        try:
            validate_profile(data, graph=graph, raise_on_error=True)
        except ProfileValidationError as e:
            raise ProfileError(f"{path} is not a usable profile:\n{e}") from e

    return Student.from_dict(data)


def load_all_profiles(
    directory: str | Path = PROFILES_DIR,
    graph: nx.DiGraph | None = None,
    validate: bool = True,
) -> dict[str, Student]:
    directory = Path(directory)
    files = sorted(glob(str(directory / "*.json")))
    if not files:
        raise ProfileError(f"No student profile files found in {directory}")

    students: dict[str, Student] = {}
    for file_path in files:
        student = load_profile(file_path, graph=graph, validate=validate)
        if student.student_id in students:
            raise ProfileError(
                f"Duplicate student_id '{student.student_id}' found in {file_path}."
            )
        students[student.student_id] = student
    return students


# Human-readable reporting

def profile_overview(student: Student, graph: nx.DiGraph) -> dict:
    completed = student.completed_concepts()
    eligible = student.eligible_concepts(graph)
    return {
        "student_id": student.student_id,
        "name": student.name,
        "persona": student.metadata.get("persona", "unknown"),
        "touched": len(student.progress),
        "mastered": len(completed),
        "average_mastery": student.average_mastery(),
        "study_hours": student.total_study_hours(),
        "eligible": len(eligible),
        "events": len(student.history),
    }


def format_profile_comparison(students: dict[str, Student], graph: nx.DiGraph) -> str:
    from stepzero.recommendation import recommend_next

    header = (
        f"{'Persona':<16}{'Touched':>8}{'Mastered':>9}{'AvgMast':>9}"
        f"{'Hours':>9}{'Eligible':>9}  Top recommendation"
    )
    lines = [header, "=" * len(header)]

    for student in students.values():
        overview = profile_overview(student, graph)
        recommendations = recommend_next(graph, student, top_n=1)
        if recommendations:
            top = recommendations[0]
            label = graph.nodes[top.concept_id].get("name", top.concept_id)
            top_text = f"{label} ({top.score:.3f})"
        else:
            top_text = "none, curriculum exhausted"

        lines.append(
            f"{overview['persona']:<16}{overview['touched']:>8}{overview['mastered']:>9}"
            f"{overview['average_mastery']:>9.3f}{overview['study_hours']:>9.1f}"
            f"{overview['eligible']:>9}  {top_text}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse
    import sys

    from stepzero.graph_builder import build_graph, GraphBuildError
    from stepzero.recommendation import recommend_next

    parser = argparse.ArgumentParser(
        description="Generate, validate, and compare the synthetic Project Step Zero learner profiles."
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="Regenerate the profile files in data/students from the persona definitions.",
    )
    parser.add_argument(
        "--profiles-dir", default=None,
        help="Optional path to a data/students-style directory. Defaults to the project's data/students.",
    )
    parser.add_argument(
        "--detail", action="store_true",
        help="Also print the top recommendations and strongest and weakest concepts per profile.",
    )
    args = parser.parse_args()

    try:
        curriculum = build_graph()
    except GraphBuildError as e:
        print(f"Could not build graph: {e}")
        sys.exit(1)

    target_dir = Path(args.profiles_dir) if args.profiles_dir else PROFILES_DIR

    if args.generate:
        paths = write_profile_files(curriculum, output_dir=target_dir)
        print(f"Wrote {len(paths)} profile(s) to {target_dir}:")
        for path in paths:
            print(f"  {path.name}")
        print()

    try:
        profiles = load_all_profiles(target_dir, graph=curriculum)
    except ProfileError as e:
        print(f"Could not load profiles: {e}")
        sys.exit(1)

    print("All profiles below are synthetic research personas, not observed student data.\n")
    print(format_profile_comparison(profiles, curriculum))

    if args.detail:
        for student in profiles.values():
            print()
            print(f"--> {student.name} ({student.metadata.get('persona')})")
            scored = sorted(
                student.progress.values(), key=lambda p: (-p.mastery_score, p.concept_id)
            )
            strongest = scored[:3]
            weakest = scored[-3:]
            print("   strongest:")
            for record in strongest:
                print(f"     {record.mastery_score:.2f}  {record.concept_id}")
            print("   weakest:")
            for record in weakest:
                print(f"     {record.mastery_score:.2f}  {record.concept_id}")
            print("   next recommended:")
            for rec in recommend_next(curriculum, student, top_n=3):
                name = curriculum.nodes[rec.concept_id].get("name", rec.concept_id)
                print(f"     {rec.score:.3f}  {name}")
